# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('name', 'year')]),
        ),
    ]
